# Generated by Django 5.1.4 on 2024-12-14 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, max_length=4096, null=True, verbose_name="Описание продукта"
            ),
        ),
    ]
