# Generated by Django 5.1.4 on 2024-12-14 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="photo",
            new_name="image",
        ),
    ]
