# Generated by Django 5.1.4 on 2024-12-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_rename_photo_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание продукта"
            ),
        ),
    ]
