# Generated by Django 5.1.4 on 2024-12-12 11:36

import apps.news.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NewsChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на канал"
                    ),
                ),
                (
                    "tg_username",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="TG Username",
                    ),
                ),
                (
                    "tg_id",
                    models.BigIntegerField(
                        validators=[apps.news.validators.validate_tg_id],
                        verbose_name="ID Telegram",
                    ),
                ),
            ],
            options={
                "verbose_name": "Канал новостей",
                "verbose_name_plural": "Каналы новостей",
            },
        ),
        migrations.CreateModel(
            name="NewsTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("param_value", models.IntegerField(verbose_name="Значение")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NewsType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("param_value", models.IntegerField(verbose_name="Значение")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NewsFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "country",
                    models.ManyToManyField(to="news.country", verbose_name="Страна"),
                ),
                (
                    "language",
                    models.ManyToManyField(to="news.language", verbose_name="Язык"),
                ),
                (
                    "news_theme",
                    models.ManyToManyField(
                        to="news.newstheme", verbose_name="Тема новости"
                    ),
                ),
                (
                    "news_type",
                    models.ManyToManyField(
                        to="news.newstype", verbose_name="Тип новости"
                    ),
                ),
                (
                    "region",
                    models.ManyToManyField(to="news.region", verbose_name="Регион"),
                ),
            ],
            options={
                "verbose_name": "Фильтр новостей",
                "verbose_name_plural": "Фильтры новостей",
            },
        ),
    ]
