# Generated by Django 5.1.4 on 2024-12-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="name",
            field=models.CharField(default=1, max_length=255, verbose_name="Название"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="country",
            name="param_value",
            field=models.IntegerField(default=1, verbose_name="Значение"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="language",
            name="name",
            field=models.CharField(default=1, max_length=255, verbose_name="Название"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="language",
            name="param_value",
            field=models.IntegerField(default=1, verbose_name="Значение"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="newstype",
            name="name",
            field=models.CharField(default=1, max_length=255, verbose_name="Название"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="newstype",
            name="param_value",
            field=models.IntegerField(default=1, verbose_name="Значение"),
            preserve_default=False,
        ),
    ]
