# Generated by Django 5.1.4 on 2024-12-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_country_name_country_param_value_language_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="param_value",
            field=models.CharField(verbose_name="Значение"),
        ),
    ]
