# Generated by Django 5.1.4 on 2024-12-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_newschannel_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsfilter",
            name="country",
        ),
        migrations.RemoveField(
            model_name="newsfilter",
            name="language",
        ),
        migrations.RemoveField(
            model_name="newsfilter",
            name="news_theme",
        ),
        migrations.RemoveField(
            model_name="newsfilter",
            name="news_type",
        ),
        migrations.RemoveField(
            model_name="newsfilter",
            name="region",
        ),
        migrations.AddField(
            model_name="newsfilter",
            name="url",
            field=models.URLField(default=1, verbose_name="Ссылка на фильтр"),
            preserve_default=False,
        ),
    ]
