# Generated by Django 5.1.4 on 2024-12-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_pendingnews"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="newsfilter",
            table_comment="Если выбран хотя бы один параметр, то новости будут фильтроваться по нему.",
        ),
        migrations.AddField(
            model_name="newsfilter",
            name="country",
            field=models.ManyToManyField(
                blank=True, to="news.country", verbose_name="Страна"
            ),
        ),
        migrations.AddField(
            model_name="newsfilter",
            name="news_theme",
            field=models.ManyToManyField(
                blank=True, to="news.newstheme", verbose_name="Тема новости"
            ),
        ),
        migrations.AddField(
            model_name="newsfilter",
            name="news_type",
            field=models.ManyToManyField(
                blank=True, to="news.newstype", verbose_name="Тип новости"
            ),
        ),
        migrations.AddField(
            model_name="newsfilter",
            name="region",
            field=models.ManyToManyField(
                blank=True, to="news.region", verbose_name="Регион"
            ),
        ),
        migrations.AlterField(
            model_name="newsfilter",
            name="url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Ссылка на фильтр"
            ),
        ),
    ]
