# Generated by Django 5.1.4 on 2025-01-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_alter_newsfilter_table_comment_newsfilter_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsfilter",
            name="is_url",
            field=models.BooleanField(
                default=False,
                help_text="Если выбрано, то новости будут фильтроваться по ссылке.",
                verbose_name="Фильтр по ссылке",
            ),
        ),
    ]
