# Generated by Django 5.1.4 on 2025-01-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0008_newsfilter_is_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsfilter",
            name="country",
        ),
        migrations.RemoveField(
            model_name="newsfilter",
            name="news_theme",
        ),
        migrations.RemoveField(
            model_name="newsfilter",
            name="news_type",
        ),
        migrations.RemoveField(
            model_name="newsfilter",
            name="region",
        ),
        migrations.AlterField(
            model_name="newsfilter",
            name="is_url",
            field=models.BooleanField(
                default=True,
                help_text="Если выбрано, то новости будут фильтроваться по ссылке.",
                verbose_name="Фильтр по ссылке",
            ),
        ),
    ]
