# Generated by Django 5.1.4 on 2025-01-06 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0009_remove_newsfilter_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsfilter",
            name="is_url",
        ),
    ]
