# Generated by Django 5.1.4 on 2025-01-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0010_remove_newsfilter_is_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=8, verbose_name="Код")),
            ],
            options={
                "verbose_name": "OTP",
                "verbose_name_plural": "OTP",
            },
        ),
    ]
