# Generated by Django 5.1.4 on 2024-12-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="ID Telegram"
                    ),
                ),
                (
                    "tg_username",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="TG Username",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Полное имя"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата регистрации"
                    ),
                ),
            ],
            options={
                "verbose_name": "TG-Пользователь",
                "verbose_name_plural": "TG-Пользователи",
            },
        ),
    ]
