# Generated by Django 5.1.4 on 2024-12-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="registred",
            field=models.BooleanField(default=False, verbose_name="Зарегистрирован"),
        ),
    ]
