# Generated by Django 5.1.4 on 2024-12-12 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lottery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название розыгрыша"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание розыгрыша"
                    ),
                ),
                (
                    "fin_date",
                    models.DateTimeField(verbose_name="Время окончания розыгрыша"),
                ),
                (
                    "is_finished",
                    models.BooleanField(default=False, verbose_name="Завершено"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="lotteries",
                        to="users.telegramuser",
                        verbose_name="Участники розыгрыша",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.telegramuser",
                        verbose_name="Победитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Розыгрыш",
                "verbose_name_plural": "Розыгрыши",
                "ordering": ["-fin_date"],
            },
        ),
    ]
