# Generated by Django 5.1.4 on 2024-12-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lottery",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="lotteries/",
                verbose_name="Фото розыгрыша",
            ),
        ),
    ]
