# Generated by Django 5.1.4 on 2024-12-12 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255, verbose_name="Токен бота")),
                (
                    "username",
                    models.CharField(max_length=255, verbose_name="Username бота"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность бота"),
                ),
            ],
            options={
                "verbose_name": "Бот",
                "verbose_name_plural": "Боты",
            },
        ),
        migrations.CreateModel(
            name="BotMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("photo", "Фото"),
                            ("document", "Документ"),
                            ("audio", "Аудио"),
                            ("video", "Видео"),
                        ],
                        default="photo",
                        max_length=20,
                        verbose_name="Тип медиа",
                    ),
                ),
                ("file", models.FileField(upload_to="bot_media/", verbose_name="Файл")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Медиа бота",
                "verbose_name_plural": "Медиа бота",
            },
        ),
        migrations.CreateModel(
            name="BotMessageType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.SlugField(
                        help_text="Например: 'start'",
                        max_length=100,
                        unique=True,
                        verbose_name="Название типа",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Тип сообщения бота",
                "verbose_name_plural": "Типы сообщений бота",
            },
        ),
        migrations.CreateModel(
            name="BotMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст сообщения")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="bot.botmedia",
                        verbose_name="Медиа",
                    ),
                ),
                (
                    "identifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="bot.botmessagetype",
                        verbose_name="Тип сообщения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение бота",
                "verbose_name_plural": "Сообщения бота",
            },
        ),
        migrations.CreateModel(
            name="BotButton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=100, verbose_name="Текст кнопки")),
                (
                    "button_type",
                    models.CharField(
                        choices=[
                            ("text", "Текстовая кнопка"),
                            ("callback", "Callback кнопка"),
                            ("url", "URL кнопка"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="Тип кнопки",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активность кнопки"),
                ),
                (
                    "payload",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Полезная нагрузка",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buttons",
                        to="bot.botmessage",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кнопка бота",
                "verbose_name_plural": "Кнопки бота",
                "ordering": ["order"],
            },
        ),
    ]
