# Generated by Django 5.1.4 on 2024-12-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, verbose_name="Вопрос")),
                ("answer", models.TextField(verbose_name="Ответ")),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQ",
            },
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="ID Telegram"
                    ),
                ),
                (
                    "tg_username",
                    models.CharField(max_length=255, verbose_name="TG Username"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата регистрации"
                    ),
                ),
            ],
            options={
                "verbose_name": "Менеджер",
                "verbose_name_plural": "Менеджеры",
            },
        ),
        migrations.DeleteModel(
            name="Bot",
        ),
        migrations.RemoveField(
            model_name="botmessage",
            name="media",
        ),
        migrations.RemoveField(
            model_name="botmessage",
            name="identifier",
        ),
        migrations.DeleteModel(
            name="BotButton",
        ),
        migrations.DeleteModel(
            name="BotMedia",
        ),
        migrations.DeleteModel(
            name="BotMessage",
        ),
        migrations.DeleteModel(
            name="BotMessageType",
        ),
    ]
