# Generated by Django 5.1.4 on 2024-12-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broadcast", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcastmessage",
            name="scheduled_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Оставьте пустым, чтобы отправить сообщение сразу.",
                null=True,
                verbose_name="Время отправки",
            ),
        ),
    ]
